#!/usr/bin/env bash
set -euo pipefail

# TODO: Use input file name with .gif extension
output_file="${1%.*}.gif"

if [ -z "${1:-}" ]; then
    echo "Usage: $0 <input_video>"
    exit 1
fi

ffmpeg -i "$1" \
    -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
    -loop 0 "$output_file"
